title: Helen Mørken Porcelain
description: > # this means to ignore newlines until "baseurl:"
    Helen Mørken Porcelain
url: "https://helenmorken.no"
exclude: [vendor]
collections:
    products:
        output: true
        permalink: /:path/
    publicart:
        output: true
        permalink: /publicart/:path/
navigation:
    - title: Products
      url: /
    - title: Public Art
      url: /publicart/
    - title: About
      url: /about/
    - title: Contact
      url: /contact-and-sales/
# Build settings
markdown: kramdown
