title: Helen Mørken
description: > # this means to ignore newlines until "baseurl:"
    Helen Mørken
url: "https://helenmorken.no"
exclude: [vendor]
collections:
    porcelain:
        output: true
        permalink: /:path/
    sculpture:
        output: true
        permalink: /sculpture/:path/
    publicart:
        output: true
        permalink: /publicart/:path/
    landscape:
        output: true
        permalink: /landscape/:path/
    prints:
        output: true
        permalink: /prints/:path/
navigation:
    - title: Porcelain
      url: /
    - title: Ceramics
      children:
        - title: Sculpture
          url: /sculpture/
        - title: Landscape
          url: /landscape/
    - title: Prints
      url: /prints/
    - title: More
      children:
        - title: About
          url: /about/
        - title: Public Art
          url: /publicart/
        - title: Contact
          url: /contact/
        - title: Socials
          url: /socials/
# Build settings
markdown: kramdown
