title: Helen Mørken Porcelain
description: > # this means to ignore newlines until "baseurl:"
    Helen Mørken Porcelain
url: "https://helenmorken.no"
exclude: [vendor]
collections:
    products:
        output: true
        permalink: /:path/
    projects:
        output: true
        permalink: /projects/:path/

# Build settings
markdown: kramdown
